### ISSUE TITLE
Assignment 5

### ISSUE THREAD

**Issue by sfaiad** [sfaiad/Assignment-5#1]
@mdscheuerell 

Hello, Mark! 

For assignment 5, I created scatterplots and a violin plot. My exploratory plot was a pretty ugly scatterplot with total length (mm) on the y-axis, age on the x-axis, and location represented by color of the points. I attempted to make a more aesthetically pleasing, expository scatterplot by adding labels to the axes and changing the color, transparency, and shape of the points. The scatterplot didn't look great, as the points were overlapping quite a bit. So, I then attempted a violin plot with total length (mm) on the y-axis, location on the x-axis, and color reflecting sex. I created both an html and pdf file. 

Thank you!

**Comment by mdscheuerell** [comment]
This was really well done, Sara. Nice work!
